#!/usr/bin/env python3
"""One table across several forecast backbones, for `results/summary/`.

The question this answers is narrow and worth stating: **is the calibration
layer's gain a property of the layer, or of the StarNet backbone it happened to
be developed against?** If the conditional risk improvement only appears under
one forecaster, it is an interaction, not a method.

So the comparison holds the calibration layer fixed and varies the point
forecaster underneath it. Two of the backbones are StarNet ablations, which
doubles this as the periodical-embedding and attention ablation the base paper
reports.

    python scripts/compare_backbones.py results/final/wetlinks-seconds-Osnabruck-capacity \\
        results/backbones/*/wetlinks-seconds-Osnabruck-capacity \\
        --out results/summary/backbones.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd
from make_figures import calibration_frame, headline_epsilon
from make_summary import fmt

#: Backbone name -> what it is, so the table is readable without the paper.
BACKBONE_NOTES = {
    "starnet": "GRU seq2seq, periodical embedding + attention (Liu et al.)",
    "starnet_no_pe": "ablation: periodical embedding removed",
    "starnet_no_attn": "ablation: attention removed",
    "dlinear": "linear with series decomposition (Zeng et al.)",
    "patchtst": "patched transformer (Nie et al.)",
    "timesnet": "2D temporal variation blocks (Wu et al.)",
}


def row_for(directory: Path, granularity_preference: tuple[str, ...]) -> dict | None:
    path = directory / "result.json"
    if not path.exists():
        return None
    payload = json.loads(path.read_text())
    frame = calibration_frame(payload)
    if frame.empty:
        return None
    epsilon = headline_epsilon(frame, None)
    backbone = payload.get("point_metrics", {}).get("backbone", directory.parent.name)

    # Not every run swept every granularity, so take the first preference that
    # the run actually contains rather than assuming a fixed one.
    available = set(frame["granularity"])
    granularity = next((g for g in granularity_preference if g in available), "global")

    def pick(method: str, gran: str) -> pd.Series | None:
        part = frame[(frame["method"] == method) & (frame["epsilon"] == epsilon)
                     & (frame["granularity"] == gran)]
        return None if part.empty else part.iloc[0]

    point = pick("point", "global")
    static = pick("global_conformal", "global")
    ours = pick("adaptive_regime_conformal", granularity)
    if point is None or ours is None:
        return None

    return {
        "backbone": backbone,
        "note": BACKBONE_NOTES.get(backbone, ""),
        "epsilon": epsilon,
        "granularity": granularity,
        "point_MAE": point["MAE"],
        "point_OverRate": point["OverRate_global"],
        "point_P10": point["OverRate_P10"],
        "static_P10": None if static is None else static["OverRate_P10"],
        "ours_OverRate": ours["OverRate_global"],
        "ours_P10": ours["OverRate_P10"],
        "ours_MAE": ours["MAE"],
        # The claim under test, expressed as the thing that should be stable
        # across backbones if the layer is a method.
        "P10_reduction": (point["OverRate_P10"] - ours["OverRate_P10"])
                         / point["OverRate_P10"],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("directories", type=Path, nargs="+")
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)

    preference = ("level+candidates", "level", "full", "global")
    rows = [r for d in args.directories if (r := row_for(d, preference)) is not None]
    if not rows:
        raise SystemExit("no readable runs among the given directories")

    frame = pd.DataFrame(rows)
    # StarNet first, then its ablations, then the external baselines, so the
    # table reads in the order the argument is made.
    order = list(BACKBONE_NOTES)
    frame["_order"] = frame["backbone"].apply(
        lambda b: order.index(b) if b in order else len(order)
    )
    frame = frame.sort_values("_order").drop(columns="_order")

    epsilon = frame["epsilon"].iloc[0]
    lines = [
        "# Backbone comparison",
        "",
        "Generated by `scripts/compare_backbones.py`. The calibration layer is held",
        "fixed and the point forecaster underneath it is varied, to test whether the",
        "conditional risk improvement is a property of the layer or an interaction",
        "with the one backbone it was developed against.",
        "",
        f"Osnabruck per-second capacity, budget {epsilon:.2f}, 13,530 test decisions.",
        "`ours` is adaptive regime conformal.",
        "",
        "| backbone | what it is | point MAE | point OverRate | point P10 | static P10 | ours OverRate | ours P10 | ours MAE | P10 reduction |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for _, r in frame.iterrows():
        lines.append(
            f"| `{r['backbone']}` | {r['note']} | {fmt(r['point_MAE'], 2)} | "
            f"{fmt(r['point_OverRate'])} | {fmt(r['point_P10'])} | "
            f"{fmt(r['static_P10'])} | {fmt(r['ours_OverRate'])} | "
            f"{fmt(r['ours_P10'])} | {fmt(r['ours_MAE'], 2)} | "
            f"{r['P10_reduction'] * 100:.1f}% |"
        )

    reductions = frame["P10_reduction"]
    lines += [
        "",
        "## Reading it",
        "",
        f"P10 reduction ranges {reductions.min() * 100:.1f}% to "
        f"{reductions.max() * 100:.1f}% across {len(frame)} backbones "
        f"(mean {reductions.mean() * 100:.1f}%).",
        "",
        "The narrower that range, the more the layer is a property of the",
        "calibration rather than of any one forecaster. A backbone whose point",
        "forecast is already conservative has less headroom and should show a",
        "smaller reduction; that is expected and is not evidence against the layer.",
    ]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} across {len(frame)} backbones")
    print(frame[["backbone", "point_P10", "ours_P10", "P10_reduction"]].round(4)
          .to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
